# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KeyAssigner.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
   # def __init__(self, parent = None):
      # super(filedialogdemo, self).__init__(parent)


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(QtWidgets.QWidget):
    def setupUi(self):
        self.setObjectName("Form")
        self.resize(400, 286)
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setGeometry(QtCore.QRect(130, 210, 300, 51))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(130, 100, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton.clicked.connect(self.getfile)
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)
        
    def getfile(self):
        _translate = QtCore.QCoreApplication.translate
        fname = QtWidgets.QFileDialog.getOpenFileName(self, 'Open file', 
        'c:\\',"Image files (*.jpg *.gif)")
        self.pushButton.setText(_translate("Form", "PushButton"))
        # self.le.setPixmap(QPixmap(fname))

    
    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.label.setText(_translate("Form", "TextLabel"))
    
    def keyPressEvent(self,event):
        # print(dir(event))
        _translate = QtCore.QCoreApplication.translate
        print(chr(event.key()))
        self.label.setText(_translate("TextLabel", chr(event.key())))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    # Form = keyAssiWidget()
    ui = Ui_Form()
    ui.setupUi()
    ui.show()
    sys.exit(app.exec_())
